name: Build Agent
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup target add aarch64-unknown-linux-musl
      - name: Build
        run: cargo build --release --target aarch64-unknown-linux-musl
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: agent-bin
          path: target/aarch64-unknown-linux-musl/release/hm_pusher
